### ISSUE TITLE
core generic error: option marq-x does not exist

### ISSUE THREAD

**Issue by anitalanet** [maknapp/vlckitSwiftSample#1]
Hi there.

I got this error after running app.. this error shown and not able to see video...

Please help me in that

Thanks in advance

**Comment by maknapp** [comment]
I made this example with mobilevlckit v2.2.1, but it looks like they updated to v2.2.2 last month. What cocoapod version of mobilevlckit are you using?

**Comment by anitalanet** [comment]
2.2.1

**Comment by anitalanet** [comment]
After some time around 20 sec later it started but with following 
 core input error: ES_OUT_RESET_PCR called
[00007fad940148b8] core decoder error: Could not convert timestamps 140383488371376, 0
[00007fad93c0f0d8] core input error: ES_OUT_RESET_PCR called
shader program 1: WARNING: Output of vertex shader 'TexCoord1' not read by fragment shader
WARNING: Output of vertex shader 'TexCoord2' not read by fragment shader

and then it hangs

**Comment by anitalanet** [comment]
It play lil bit and then hangs....the output shown in console is following
Could not convert timestamps 140383558333200, 0
[00007fad940148b8] core decoder error: Could not convert timestamps 140383558333200, 0
[00007fad940148b8] core decoder error: Could not convert timestamps 140383558333200, 0
[00007fad93c0f0d8] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1632 ms)
[00007fad93c0f0d8] core input error: ES_OUT_RESET_PCR called..

**Comment by maknapp** [comment]
Is this on a simulator or on a real device? If your mac is weak, it has a hard time playing video on high resolution simulator devices. Try using a smaller simulator like the 4s.

**Comment by anitalanet** [comment]
Hii.. i'd tried with device also and the speed of video is much better then the simulator..but still it stuck after each 2 or 3 seconds for while.. its not play smoothly 

What should be the reason. ?

**Comment by maknapp** [comment]
Can you play the video fine with VLC? Perhaps your internet is too slow?

**Comment by anitalanet** [comment]
Video is playing fine and my internet connection also fine but the video is not playing smoothly.. as i previoisly mention that it is stuck while playing and i am also observes that the frames are not in sequences...sometime the video play too fast and somethime its play stucky

**Comment by maknapp** [comment]
Change [this line](https://github.com/maknapp/vlckitSwiftSample/blob/master/vlckitSwiftSample/ViewController.swift#L14) to:
`var mediaPlayer = VLCMediaPlayer(options: ["-vvvv"])`

This will enabled debug logs. Hopefully that will give some more information. [Here](http://pastebin.com/bvatFiQJ) are my debug logs when the video is playing normally for you to compare with.

**Comment by anitalanet** [comment]
Hii.. thanks for ur greate support.. i have already use above mention command...but still the video is stuck and some time play too speedy...

Please @maknapp  help me in that...

Thanks in advance

**Comment by anitalanet** [comment]
Hii. finally i am able to play video in smooth way..thanks for ur great help.. appriciated...
I have one another query also :  i need to display the loader till the video is not ready for the state for playing and dismiss after the video is ready for play.. how can i achive this with ur given library...

Like AVPlayer has the KVOObserver ...is there any kind of observer where i can used for the display loader..

Thanks in advance

**Comment by anitalanet** [comment]
Hii. finally i am able to play video in smooth way..thanks for ur great help.. appriciated...
I have one another query also :  i need to display the loader till the video is not ready for the state for playing and dismiss after the video is ready for play.. how can i achive this with ur given library...

Like AVPlayer has the KVOObserver ...is there any kind of observer where i can used for the display loader..

Thanks in advance

**Comment by maknapp** [comment]
Make `ViewController` use `VLCMediaPlayerDelegate` for events. You can look in the MobileVLCKit pod source to see what is available (it is in Obj C though).

**Comment by anitalanet** [comment]
Thanks Its works .
