### ISSUE TITLE
pod install问题

### ISSUE THREAD

**Issue by SpiritualPlayer** [maknapp/vlckitSwiftSample#12]
楼主你好，我这边下载demo以后，执行pod install,但是停顿在Installing MobileVLCKit(2.2.2),你遇到这种情况吗？怎么解决呢？

**Comment by maknapp** [comment]
Using google translate, I'm assuming you are asking about the `pod install` command freezing. You can try doing `pod install --verbose` to see what is getting stuck, and then search that exact issue. The MobileVLCKit is very large and may just be taking a while to download.

This is not an issue with this repo, closing.
