### ISSUE TITLE
libvlc_MetadataCancel_Issue

### ISSUE THREAD

**Issue by ramayash** [maknapp/vlckitSwiftSample#14]
Please try to resolved the given following issue related with MobileVLCKit in xcode 9.2 , swift4.0 .
1.libvlc_MetadataCancel(creating player instance with private library as options were given)
2.playlist_preparser_Cancel
3.vlc_custom_create
Issue occur when try to play MobileVLCKit more than one time.

<img width="268" alt="screen shot 2018-06-13 at 10 51 19 am" src="https://user-images.githubusercontent.com/20200124/41342843-d2b08290-6f1a-11e8-998f-1f444a71ee50.png">

**Comment by maknapp** [comment]
I am not quite sure what you are trying to do - it would be helpful if you could post a code example to recreate the issue. This sounds like an issue for working with vlckit, not an issue with this repo. You are more likely to get an answer if you post your question [here on stackoverflow libvlc](https://stackoverflow.com/questions/tagged/libvlc).
