### ISSUE TITLE
Set options for live rtsp stream to reduce delay

### ISSUE THREAD

**Issue by Sushma7785** [maknapp/vlckitSwiftSample#15]
There is some delay while playing a live rtsp stream. Is there a way to set caching/buffering options in the player to reduce the latency?

**Comment by maknapp** [comment]
I have added an example showing how to set media options [here](https://github.com/maknapp/vlckitSwiftSample/blob/da0153b1123ed785a66d53536539e99a54c85924/vlckitSwiftSample/ViewController.swift#L61-L65). Note that I have updated to Swift 4 and MobileVLCKit 3.1.0.
