### ISSUE TITLE
Steps to import MobileVLCKit into Xcode

### ISSUE THREAD

**Issue by HarryDao** [maknapp/vlckitSwiftSample#16]
Hi Mark,

I am trying to import MobileVLCKit to my project. I saw that your app vlckitSwiftSample works fine, but I dont know how to replicate it. I still cant find VLCPlayerDelegate on Xcode.

Steps I did:
- add MobileVLCKit to pod and install
- disable bitcode
- create header-bridging.h file to import MObileVLCKit
- manually add the MobileVLCKit and libstdc++.6.tbd in Build Phase

If I copied your Other Link Flags to mine, I got error of "no such file or directory: 'MobileVLCKit'"

Can you please help brief me on how to manage to import the framework? 

Thank you so much. I really appreciate your help.

Best regards,
Dao Nguyen Dang Khoa(Harry)

**Comment by maknapp** [comment]
Have you created the `empty.cpp` and `empty.hpp` files? Those are required to use Objective C libraries. Have you opened the project with the .xcworkspace file not the .xcproject file?

You could also try creating a new project and see if you can get MobileVLCKit working - there might be something in your existing project causing issues.

**Comment by HarryDao** [comment]
Thank Mark. I found the problem. I forgot to include the file header path in Build Settings. It seems that I can VLCMediaPlayerDelegate now without file empty.cpp and empty.hpp. Thank you very much for your help.
