### ISSUE TITLE
I'm unable to set a video in a repeat mode in VLCMediaPlayer

### ISSUE THREAD

**Issue by NaveedBIM** [maknapp/vlckitSwiftSample#20]
'VLCMediaPlayer' has no member 'repeatMode'

I'm currently setting as

mediaPlayer.repeatMode = VLCRepeatMode.repeatCurrentItem

**Comment by maknapp** [comment]
Repeat appears to be in `VLCMediaListPlayer` not `VLCMediaPlayer`. I do not have a Mac to test this out though. If you can't get it working try asking on stackoverflow.com as this is not really an issue for this.

**Comment by NaveedBIM** [comment]
I'm using this code but video is not playing.

        let media = VLCMedia(url: videoURL)
        let mediaList = VLCMediaList(array: [media])
        mediaPlayerList.mediaPlayer.delegate = self
        mediaPlayerList.mediaPlayer.drawable = self.videoView
        mediaPlayerList.mediaList = mediaList
        mediaPlayerList.repeatMode = .repeatCurrentItem
        mediaPlayerList.play()
