### ISSUE TITLE
Video is not playing.

### ISSUE THREAD

**Issue by IvanStanojevic** [maknapp/vlckitSwiftSample#23]
Here are my codes.

`let stringUrl = "rtsp://192.168.1.1:8554/live"
        let url = URL.init(string: stringUrl)
        let media = VLCMedia(url: url!)
        
        media.addOptions([
            "network-caching": 0, 
            "rtsp-caching": 50,
            "rtsp-tcp": 1,
            "no-audio": 1            
        ])
        
        mediaPlayer.media = media
        mediaPlayer.delegate = self
        mediaPlayer.drawable = self.playerView
        mediaPlayer.play()`

But video is not displaying and I can see error logs as below.

> [h264 @ 0x128035e00] get_buffer() failed
[h264 @ 0x128035e00] thread_get_buffer() failed
[h264 @ 0x128035e00] decode_slice_header error
[h264 @ 0x128035e00] no frame!
[h264 @ 0x1280e8e00] get_buffer() failed
[h264 @ 0x1280e8e00] thread_get_buffer() failed
[h264 @ 0x1280e8e00] decode_slice_header error
[h264 @ 0x1280e8e00] no frame!
[h264 @ 0x1280e9400] get_buffer() failed
[h264 @ 0x1280e9400] thread_get_buffer() failed
[h264 @ 0x1280e9400] decode_slice_header error
[h264 @ 0x1280e9400] no frame!

Please help me how can I figure out this.
Thanks
Ivan

**Comment by maknapp** [comment]
I'm guessing the errors mean it cannot see the video stream. Confirm the URL is visible to your device. Asking this on Stackoverflow will probably get you a better answer.
