### ISSUE TITLE
mobileVlcKit don't support avi, mov mp4... ?? 

### ISSUE THREAD

**Issue by shindonghyeok** [maknapp/vlckitSwiftSample#4]
i can play .ts file on your vlc kit but i can't play .mov, .avi.... it doesn't support these format? or there are any solution to play these format file?

**Comment by maknapp** [comment]
It should be able to play everything that VLC can play. I know .mov works. What errors are you getting?

**Comment by shindonghyeok** [comment]
when i use .mov file i got a "[mov,mp4,m4a,3gp,3g2,mj2 @ 0x12f176000] stream 1, offset 0x24: partial file
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x12f176000] stream 1, offset 0x24: partial file" errors 
and 
using .avi, [00000001464d8598] avi demux error: no key frame set for track 0
[00000001464d8598] avi demux error: no key frame set for track 1
[00000001464d8598] avi demux error: no key frame set for track 0
[00000001464d8598] avi demux error: no key frame set for track 1
[h264 @ 0x14507ce00] non-existing PPS 0 referenced
[h264 @ 0x14507ce00] decode_slice_header error
[h264 @ 0x14507ce00] no frame!
[h264 @ 0x145092e00] non-existing PPS 0 referenced
[h264 @ 0x145092e00] decode_slice_header error
[h264 @ 0x145092e00] no frame!
[h264 @ 0x145093400] non-existing PPS 0 referenced
[h264 @ 0x145093400] decode_slice_header error
[h264 @ 0x145093400] no frame!
[h264 @ 0x14507ce00] non-existing PPS 0 referenced
[h264 @ 0x14507ce00] decode_slice_header error
[h264 @ 0x14507ce00] no frame!
[h264 @ 0x145092e00] non-existing PPS 0 referenced
[h264 @ 0x145092e00] decode_slice_header error
[h264 @ 0x145092e00] no frame!
[h264 @ 0x145093400] non-existing PPS 0 referenced
[h264 @ 0x145093400] decode_slice_header error
[h264 @ 0x145093400] no frame!
[h264 @ 0x14507ce00] non-existing PPS 0 referenced
[h264 @ 0x14507ce00] decode_slice_header error
[h264 @ 0x14507ce00] no frame!
[h264 @ 0x145092e00] non-existing PPS 0 referenced
[h264 @ 0x145092e00] decode_slice_header error
[h264 @ 0x145092e00] no frame!
[h264 @ 0x145093400] non-existing PPS 0 referenced
[h264 @ 0x145093400] decode_slice_header error
[h264 @ 0x145093400] no frame!
[h264 @ 0x14507ce00] non-existing PPS 0 referenced
[h264 @ 0x14507ce00] decode_slice_header error
[h264 @ 0x14507ce00] no frame!
[h264 @ 0x145092e00] non-existing PPS 0 referenced
[h264 @ 0x145092e00] decode_slice_header error
[h264 @ 0x145092e00] no frame!
shader program 1: WARNING: Output of vertex shader 'TexCoord1' not read by fragment shader
WARNING: Output of vertex shader 'TexCoord2' not read by fragment shader

[00000001464c39b8] core vout display error: Failed to set on top

**Comment by shindonghyeok** [comment]
oh i have someting to tell you, there are 3 .avi file, one thing can play, but other things can't play... 
then.. the reason is file?  i mean i guess if file has some problem... how do you think?

**Comment by maknapp** [comment]
It sounds like an issue with the video file. Try looking at the error output when playing the file with desktop VLC or ffmpeg.
