### ISSUE TITLE
how to know when video is finished?? 

### ISSUE THREAD

**Issue by shindonghyeok** [maknapp/vlckitSwiftSample#5]
i would like to know the time that video is finished.. 

how can i do that??

**Comment by maknapp** [comment]
You have to implement `VLCMediaPlayerDelegate`

Example:

``` swift
class ViewController: UIViewController, VLCMediaPlayerDelegate {

    func mediaPlayerStateChanged(notification: NSNotification) {
        if mediaPlayer == nil {
            return
        }

        let state = mediaPlayer.state()

        if state == VLCMediaPlayerStateError {
            print("Error trying to play video!")
        }
        else if state == VLCMediaPlayerStateEnded || state == VLCMediaPlayerStateStopped {
            print("Video is done playing")
        }
    }

    func mediaPlayerTimeChanged(notification: NSNotification) {}

}
```

**Comment by shindonghyeok** [comment]
i wrote "VLCMediaPlayerStateError, VLCMediaPlayerStateEnded, VLCMediaPlayerStateStopped" but these got error... so i rewrote VLCMediaPlayerState.Stopped like these... then error was gone. 
and how can i call 'mediaPlayerStateChanged' function? should i send some notification? then how can i??

**Comment by shindonghyeok** [comment]
sorry.. i think my meaning was little ambiguous... what i want to know is exactly that i want to know video finish time and after video finished , i want to replay the video... this is what i want to do! 
thank you^^

**Comment by maknapp** [comment]
You do not call mediaPlayerStateChanged - it gets called when the state changes. The player executes that function when the state changes. [This line](https://github.com/maknapp/vlckitSwiftSample/blob/master/vlckitSwiftSample/ViewController.swift#L51) tells mediaPlayer what class contains the delegate functions (`mediaPlayerStateChanged`, and `mediaPlayerTimeChanged`).

**Comment by shindonghyeok** [comment]
oh! i did! thank you~! i have one more problem.. hahah.. do you know how to replay the video which is finished??

**Comment by sanjukhunt** [comment]
for replay set same media to the media player.

It's work for me

**Comment by adarshroy** [comment]
@maknapp  @sanjukhunt  VLCMediaPlayerStateEnded never gets called at all. 
VLCMediaPlayerStateStopped gets called whenever the video stops playing by either stopping manually or play-ended.
I need to get the specific event of play-ended.

**Comment by maknapp** [comment]
This may be due to [this issue](https://code.videolan.org/videolan/VLCKit/issues/32) in VLCKit. It appears to have been fixed in the v3 branch. This sample project is still on VLCKit v2.2.2, so perhaps try updating to the pre-release v3 branch and see if that fixes it.

**Comment by adarshroy** [comment]
Tried to install via CocoaPods
Did 'pod 'MobileVLCKit', and pod install
This command always gives the latest version available. So I guess, v2.2.2 is the latest one available

**Comment by fukemy** [comment]
hello. here is my code

```
func mediaPlayerStateChanged(_ aNotification: Notification!) {
        print("mediaPlayerStateChanged \(aNotification)")
    
        let state : VLCMediaPlayerState = player.state
        
        if state == .error {
            print("Error!")
        }
        
        if state == .buffering {
            print("buffering!")
        }
        
        if state == .opening {
            print("opening!")
        }
        
        if state == .playing {
            print("Error trying to play video!")
            playerView.frame.size =  player.videoSize;
        }
    }
```
only state buffering is called. other is not called even video is playing.. plz help

**Comment by joshuadiezmo** [comment]
@fukemy any update on your problem> I encounter same problem

**Comment by fukemy** [comment]
@joshuadiezmo im used ijkplayer instead of vlc
