### ISSUE TITLE
Custom Controls are not displaying in MobileVLCKit media player

### ISSUE THREAD

**Issue by mahabaleshwarhnr** [maknapp/vlckitSwiftSample#7]
Did you able to add custom controls to media player? I have added my custom controls. But not displaying. Please help me to find the solution. Please see my code [http://stackoverflow.com/questions/41222518/custom-controls-are-not-displaying-in-mobilevlckit-media-player](url)

**Comment by sanjukhunt** [comment]
You can add custom control outside of the playerview and it will display for you.
