### ISSUE TITLE
how to change basic? protocol  

### ISSUE THREAD

**Issue by shindonghyeok** [maknapp/vlckitSwiftSample#9]
I can change basic protocol (http) to rtsp in vlc for pc. like this, how can i change protocol in vlc for mobile in swift? what i want to do is I want to send url using udp, so i have to change basic protocol(http) to rtp or rtsp... 

please help me ...

**Comment by maknapp** [comment]
[vlc stream rtsp?](https://www.google.com/#q=vlc+stream+rtsp&*)

**Comment by shindonghyeok** [comment]
i got a solution  thank you!!
